name: Docker Compose CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Stop existing containers
        run: docker-compose down || true
        continue-on-error: true

      - name: Build and start containers in detached mode
        run: |
          docker-compose build
          docker-compose up -d
